script/queries/2015_plans_2014_year.rb
script/queries/Premium_amounts.rb
script/queries/broker_error.rb
script/queries/check_shop_enroll.rb
script/queries/create_renewals.rb
script/queries/dupe_delete.rb
script/queries/employer_export.rb
script/queries/error_trans_all.rb
script/queries/generate_individual_audits.rb
script/queries/generate_renewal_plan_years.rb
script/queries/generate_shop_audits.rb
script/queries/last_transaction_file_type.rb
script/queries/mult_pol_zoheb.rb
script/queries/multiple_subscribers.rb
script/queries/nfp_audit_report.rb
script/queries/nfp_audit_report_non_congress.rb
script/queries/policies_missing_transmissions.rb
script/queries/policy_count.rb
script/queries/saadi_report.rb
script/queries/steven_new.rb

I've made multiple changes to some of the scripts we've been using to make them more user friendly.

Zoheb's modifications to scripts plus new scripts he's written

---

script/queries/create_ivl_renewals_assisted.rb

Still working on ensuring APTC is right. I also moved the script to the appropriate folder.

Added fix to ensure that 2015 variant is carried over to 2016 variant

---

script/queries/steven_new.rb

Adding a change to Stephen Haines's report.

Add relationship field to stephen haines report

---

script/queries/2016_renewal_checker.rb
script/queries/correlate_audits.rb

updating the audit script and the renewal checker with trivial changes.

minor changes to scripts

---

script/queries/create_renewals.rb
script/queries/employer_export.rb
script/queries/generate_individual_audits.rb
script/queries/generate_renewal_plan_years.rb
script/queries/generate_shop_audits.rb
script/queries/nfp_audit_report.rb
script/queries/policies_missing_transmissions.rb
script/queries/saadi_report.rb
script/queries/set_authority_members.rb

includes changes to 
- add gender field to saadi report 
- add counters to several reports 
- update some of the scripts to ignore unwanted policies.

Updating several generated reports

---

app/models/canonical_vocabulary/enrollment_serializer.rb

@TreyE please see these modifications.

Refs #6045 Modifications to Enrollment Serializer

---

script/migrations/policy_cancel_no_transmission.rb
script/queries/enrollment_audit_report.rb
script/queries/generate_shop_audits.rb
script/queries/saadi_report.rb
script/queries/steven_new.rb

6216 commits are for script that's currently in progress. 
6252 code is completed.

Refs #6216 and #6252

---

script/queries/steven_new.rb

Per a request from Stephen Haines

Remove Person ID field

---

script/queries/duplicate_addresses_report.rb
script/queries/termination_sender_report.rb
script/queries/transaction_error_report.rb

* https://devops.dchbx.org/redmine/issues/7625
* Pranab Khanal
* Pranab Khanal
* Trey Evans
* Matt Williams
* Code is a script that just needs to run on production data.

Glue Mailing Address/Home Address Report

---

script/queries/current_aptc_report.rb

* https://devops.dchbx.org/redmine/issues/7836
* Code needs to accurately grab both aptc and csr policies, so make sure queries and filtering are accurate.
* Can be run on Glue locally.
* (for release manager and/or build manager)

Refs #7836 adding current aptc report

---

script/queries/current_aptc_report.rb
script/queries/spreadsheet_cv_generator.rb
script/queries/steven_new.rb
script/queries/zero_premium_policies.rb

* https://devops.dchbx.org/redmine/issues/8178
*3.0.0
---
* Code should output a single report in CSV format. 
* Query should return any policy that has a zero premium in some form. 
* (For testing locally)
* Should be run daily against prod data.

Pull request for 8178 and other code

---

script/queries/enrollment_audit_report.rb
script/queries/transaction_error_report.rb

Refs #6216

---

script/migrations/add_comments.rb
script/queries/current_aptc_report.rb
script/queries/employer_broker_info.rb
script/queries/enrollment_audit_report.rb
script/queries/saadi_report.rb
script/queries/shop_currently_active_policies.rb

Code for data-6216
Code to alter Saadi report by adding benefit status code and relationship code.
Code to add csr percentage to current aptc report (for chris wiseman)
Code to return all broker data by SHOP plan year (for stephen haines) 
Code to find all currently active shop policies.

Various Scripts

---

script/queries/multiple_people_report.rb
spec/factories/policies.rb
spec/script/queries/multiple_people_report_spec.rb

Redmine: 
* https://devops.dchbx.org/redmine/issues/8123
Rspec
* Finished in 11.22 seconds (files took 9.43 seconds to load)
1121 examples, 2 failures, 14 pending
Deployment Notes 
* Script takes a while to run since it's iterating over the entire person collection in Glue (~15 minutes). 
* It should return three CSV files, which should be provided to business: one has all potential conflicts, another has just SHOP, and another has just individual market.

Refs #8123 Final Version of Script and Specs

---

script/queries/current_aptc_report.rb

Refs #8522 update report to add name fields and premium total

---

db/seedfiles/import_next_year_plans_from_json.rb
db/seedfiles/map_current_year_plans_to_renewal_plans_from_json.rb

- Step 1 place the 2016 and 2017 plan json files in /db/seedfiles/. Names MUST BE 2016_plans.json and 2017_plans.json
- Step 2 `rails r db/seedfiles/import_next_year_plans_from_json.rb`
- Step 3 `rails r db/seedfiles/map_current_year_plans_to_renewal_plans_from_json.rb`

11531 load 2017 plans

---

script/queries/report_for_curam_11093.rb

Ticket: https://devops.dchbx.org/redmine/issues/11093

Data 11093- Report for Curam.

---

script/queries/report_of_ees_not_renewing.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14376](https://devops.dchbx.org/redmine/issues/14376) |
| Ticket Author | @LavinaNicole |

14376: Report of EEs not renewing 

---

script/queries/cancel_termination_reinstate_data.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14341](https://devops.dchbx.org/redmine/issues/14341) |
| Start Date | 03/02/2017 |
| Due Date | 03/07/2017  |
| Ticket Author | @ap-dc |

14341: Compile data on Cancellations, Terminations, and Re-Instatements from GlueDB

---

script/queries/unterminated_policies_with_last_rejected.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14272](https://devops.dchbx.org/redmine/issues/14272) |
| Ticket Author | Alix Pereira |

14272: Report request - Please generate a list of active but rejected transactions

---

app/models/listeners/enroll_query_result_handler.rb
app/models/remote_resources/enrollment_event_resource.rb
spec/models/remote_resources/enrollment_event_resource_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15389](https://devops.dchbx.org/redmine/issues/15389) |

15389: Make glue enrollment puller respect silent actions

---

app/models/enrollment_action/base.rb
app/models/enrollment_action/reselection_of_existing_coverage.rb
spec/models/enrollment_action/reselection_of_existing_coverage_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15802](https://devops.dchbx.org/redmine/issues/15802) |

15802: Handle Cases where nothing has changed during purchase

---

app/helpers/people_helper.rb
app/models/canonical_vocabulary/enrollment_serializer.rb
app/models/enrollee.rb
app/models/parsers/edi/etf/person_loop.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14033](https://devops.dchbx.org/redmine/issues/14033) |

14033: EDI DB showing child when Life partner was sent out of EDI DB

---

script/queries/generate_individual_audits.rb
script/queries/generate_shop_audits.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16139](https://devops.dchbx.org/redmine/issues/16139) |

16139: Prospective plan year for audits is being excluded when needed

---

app/models/plan_year.rb
script/queries/overlapping_plan_years.rb
spec/factories/employers.rb
spec/factories/plan_years.rb
spec/script/queries/overlapping_plan_years_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10835](https://devops.dchbx.org/redmine/issues/10835) |
| Start Date | 09/14/2016 |
| Peer Review Story Points | 0.25 |
| Ticket Author | Alix Pereira |

10835: Glue will not accept maintenance files for any ee in group Republican Mainstreet Partnership

---

app/data_migrations/remove_policy_end_date.rb
lib/mongoid_migration_task.rb
lib/tasks/remove_policy_end_date.rake
spec/data_migrations/remove_policy_end_date_spec.rb
spec/factories/policies.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16366](https://devops.dchbx.org/redmine/issues/16366) |
| Peer Review Story Points | 1 |

16366: Delta IVL Recon - policy end date updates

---

app/models/employer_event.rb
app/models/employer_events/enrollment_event_trigger.rb
app/models/employer_events/event_names.rb
app/models/employer_events/renderer.rb
app/models/listeners/employer_digest_drop_listener.rb
spec/models/employer_events/enrollment_event_trigger_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17152](https://devops.dchbx.org/redmine/issues/17152) |

17152: Glue should trigger the monthly enrollment transmission once employer events are recieved

---

app/business_processes/handlers/enrollment_event_reduce_handler.rb
app/models/external_events/enrollment_event_notification.rb
app/models/external_events/enrollment_event_notification_filters/remove_same_actions_and_select_silent.rb
spec/models/external_events/enrollment_event_notification_filters/remove_same_actions_and_select_silent_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17267](https://devops.dchbx.org/redmine/issues/17267) |

17267: In the case of multiple events being sent glue should pick the silent one

---

app/data_migrations/change_policy_end_date.rb
lib/tasks/change_policy_end_date.rake
spec/data_migrations/change_policy_end_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17266](https://devops.dchbx.org/redmine/issues/17266) |
| Ticket Author | Cherie Smith |

17266: End Date Corrections 

---

Gemfile.lock
app/models/parsers/edi/etf/reporting_categories.rb
app/models/parsers/edi/etf_validation.rb
app/models/policy.rb
app/models/queries/policies_with_no_families.rb
app/views/enrollment_events/_affected_member.xml.haml
app/views/enrollment_events/_policy.xml.haml
app/views/people/_person.xml.haml
script/migrations/family_from_policy_subscriber_script.rb
spec/models/policy_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17315](https://devops.dchbx.org/redmine/issues/17315) |

17315: Encode APTC effective date when glue generates policy XMLs

---

app/models/enrollment_action/action_publish_helper.rb
app/models/enrollment_action/assistance_change.rb
app/models/enrollment_action/assistance_comparison_helper.rb
app/models/enrollment_action/base.rb
app/models/external_events/external_policy_assistance_change.rb
app/models/policy.rb
spec/models/enrollment_action/action_publish_helper_spec.rb
spec/models/enrollment_action/assistance_change_spec.rb
spec/models/external_events/external_policy_assistance_change_spec.rb
spec/models/policy_aptc_update_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17319](https://devops.dchbx.org/redmine/issues/17319) |
| Development Story Points | 3 |

17319: Create new enrollment action in glue to represent APTC changes

---

app/models/employer_events/event_names.rb
app/models/employer_events/renderer.rb
spec/models/employer_events/renderer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17723](https://devops.dchbx.org/redmine/issues/17723) |
| Ticket Author | @saimekala07  |

17723: Handling Employers Switching Carriers Events In Glue

---

app/models/employer_events/enrollment_event_trigger.rb
app/models/employer_events/renderer.rb
spec/models/employer_events/enrollment_event_trigger_spec.rb
spec/models/employer_events/renderer_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17813](https://devops.dchbx.org/redmine/issues/17813) |

17813: Glue should only transmit employer events when there is a current or future plan year

---

app/data_migrations/change_policy_start_date.rb
lib/tasks/change_policy_start_date.rake
spec/data_migrations/change_policy_start_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17599](https://devops.dchbx.org/redmine/issues/17599) |
| Ticket Author | Azizza Brown |

17599: Correct Effective date 

---

app/business_processes/handlers/enrollment_event_persist_handler.rb
app/models/enrollment_action/active_renewal.rb
app/models/enrollment_action/base.rb
app/models/enrollment_action/initial_enrollment.rb
app/models/enrollment_action/passive_renewal.rb
spec/business_processes/handlers/enrollment_event_persist_handler_spec.rb
spec/models/enrollment_action/active_renewal_spec.rb
spec/models/enrollment_action/initial_enrollment_spec.rb
spec/models/enrollment_action/passive_renewal_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17755](https://devops.dchbx.org/redmine/issues/17755) |

17755: Prevent already existing enrollments from having automated initial enrollments sent again

---

app/data_migrations/duplicate_employer_cleanup.rb
app/data_migrations/employer_fein_change.rb
app/data_migrations/employer_fein_removal.rb
lib/tasks/duplicate_employer_cleanup.rake
lib/tasks/employer_fein_change.rake
lib/tasks/employer_fein_removal.rake
script/queries/multiple_people_report.rb
script/queries/subscribers_no_addresses.rb
spec/data_migrations/duplicate_employer_cleanup_spec.rb
spec/data_migrations/employer_fein_change_spec.rb
spec/data_migrations/employer_fein_removal_spec.rb
spec/factories/employers.rb
spec/factories/plan_years.rb
spec/factories/policies.rb
spec/factories/premium_payments.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17800](https://devops.dchbx.org/redmine/issues/17800) |

17800: Transmit 7-1 834s for Turkish Heritage Organization

---

app/data_migrations/terminate_plan_year.rb
app/models/plan_year.rb
lib/tasks/terminate_plan_year.rake
spec/data_migrations/terminate_plan_year_spec.rb
spec/factories/employers.rb
spec/factories/plan_years.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17590](https://devops.dchbx.org/redmine/issues/17590) |
| Ticket Author | Kyle Esdaille |

17590: August 2017 termination for non-payment

---

app/data_migrations/change_hbx_id.rb
app/data_migrations/merge_duplicate_people.rb
app/models/member.rb
lib/tasks/change_hbx_id.rake
lib/tasks/merge_duplicate_people.rake
spec/data_migrations/change_hbx_id_spec.rb
spec/data_migrations/merge_duplicate_people_spec.rb
spec/factories/people.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [10528](https://devops.dchbx.org/redmine/issues/10528) |
| Start Date | 08/24/2016 |
| App-Dev Priority | n/a |
| Ticket Author | Alix Pereira |

10528: Please delete the duplicate Glue user account

---

app/models/enrollment_action/renewal_dependent_drop.rb
app/models/policy.rb
spec/models/enrollment_action/active_renewal_spec.rb
spec/models/enrollment_action/renewal_dependent_drop_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [14521](https://devops.dchbx.org/redmine/issues/14521) |
| Ticket Author | Sheheryar Tariq |

14521: SHOP EDI Scenario -Renewal Dependent Drop

---

app/models/generators/reports/irs_yearly_pdf_report.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18659](https://devops.dchbx.org/redmine/issues/18659) |

18659: 1095A Generation:  Form Generation from Summary Page Policy for 2016 Void Policy Fails

---

app/helpers/policies_helper.rb
app/views/people/_policy_detail.html.erb
app/views/policies/generate_tax_document_form.html.haml
spec/helpers/policies_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18660](https://devops.dchbx.org/redmine/issues/18660) |

18660: 1095A Generation: Original Form Generation from Summary Page Policy for 2016 Policy Fails Showing Preview

---

Gemfile.lock

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19011](https://devops.dchbx.org/redmine/issues/19011) |

19011: Deploy 19009 to DC Glue

---

app/views/enrollment_events/_policy.xml.haml
script/queries/find_associated_policies_by_hbx_id.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18776](https://devops.dchbx.org/redmine/issues/18776) |

18776: Demographic changes flowing to Glue but not generating EDI files

---

Gemfile.lock
script/publish_non_payment_spreadsheet.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19193](https://devops.dchbx.org/redmine/issues/19193) |

19193: Publish termination/cancellation events present in spreadsheet from glue

---

script/queries/policies_missing_transmissions.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16463](https://devops.dchbx.org/redmine/issues/16463) |

16463: Automated Policies Missing Transmissions Report

---

app/business_processes/handlers/enrollment_event_reduce_handler.rb
app/models/external_events/enrollment_event_notification.rb
app/models/external_events/enrollment_event_notification_filters/already_processed_termination.rb
spec/business_processes/handlers/enrollment_event_reduce_handler_spec.rb
spec/models/external_events/enrollment_event_notification_filters/already_processed_termination_spec.rb
spec/models/external_events/enrollment_event_notification_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19282](https://devops.dchbx.org/redmine/issues/19282) |

19282: Glue shouldn't process terms or cancels for enrollments it has already transmitted

---

script/queries/steven_new.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18465](https://devops.dchbx.org/redmine/issues/18465) |
| App-Dev Priority | UP-1 |
| Development Story Points | 0.5 |
| Ticket Author | @ap-dc |

18465: Add "status" field to daily Glue report

---

script/queries/transaction_error_report.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16466](https://devops.dchbx.org/redmine/issues/16466) |

16466: Automate generation of Transaction Error Report

---

app/data_migrations/set_cobra_eligibility_date_for_policy.rb
app/models/policy.rb
lib/tasks/set_cobra_eligibility_date_for_policy.rake
spec/data_migrations/set_cobra_eligibility_date_for_policy_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19397](https://devops.dchbx.org/redmine/issues/19397) |

19397: Extend glue data model to identify cobra enrollments

---

app/data_migrations/change_ssn.rb
lib/tasks/change_ssn.rake
spec/data_migrations/change_ssn_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17241](https://devops.dchbx.org/redmine/issues/17241) |
| Peer Review Story Points | 1 |
| Ticket Author | Terry Smith |

17241: Update SSN 

---

Gemfile.lock

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [19914](https://devops.dchbx.org/redmine/issues/19914) |
| App-Dev Priority | UP-1 |

19914: Update DC Glue to include #19913 update to openhbx_cv2

---

app/data_migrations/change_policy_broker.rb
lib/tasks/change_policy_broker.rake
spec/data_migrations/change_policy_broker_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18859](https://devops.dchbx.org/redmine/issues/18859) |
| Ticket Author | Camille Gray |

18859: Add Broker Information to IVL Enrollment

---

script/queries/steven_new.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [16465](https://devops.dchbx.org/redmine/issues/16465) |

16465: Automate generation of Stephen Haines report

---

Gemfile.lock
app/business_processes/handlers/enrollment_event_xml_helper.rb
app/models/external_events/external_policy.rb
spec/business_processes/handlers/enrollment_event_xml_helper_spec.rb
spec/models/external_events/external_policy_spec.rb

* [10690](https://devops.dchbx.org/redmine/issues/10690)

Responsible party

---

Gemfile.lock

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20683](https://devops.dchbx.org/redmine/issues/20683) |

20683: Update gem file and deploy #20636 fix to gluedb dc

---

app/models/policy.rb
spec/factories/policies.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18512](https://devops.dchbx.org/redmine/issues/18512) |
| App-Dev Priority | UP-3 |

18512: CMS PBP SBMI:  Add EA Enrollment Kind to Glue Policy Model

---

app/models/change_sets/individual_change_set.rb
app/models/change_sets/member_relationship_change_set.rb
app/models/enrollee.rb
app/models/remote_resources/individual_resource.rb
app/models/remote_resources/person_relationship.rb
spec/models/change_sets/member_relationship_change_set_spec.rb
spec/models/remote_resources/individual_resource_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20676](https://devops.dchbx.org/redmine/issues/20676) |

20676: Enable glue to handle relationship changes and transmit policy updates

---

app/models/change_sets/individual_change_set.rb
app/models/change_sets/person_dob_change_set.rb
app/models/listeners/individual_event_listener.rb
app/models/person.rb
spec/factories/people.rb
spec/models/change_sets/individual_change_set_spec.rb
spec/models/change_sets/person_dob_change_set_spec.rb
spec/models/listeners/individual_event_listener_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [11070](https://devops.dchbx.org/redmine/issues/11070) |
| App-Dev Priority | UP-2 |
| Peer Review Story Points | 0.25 |
| Ticket Author | @DFos85 |

11070: Admin executed DOB Changes in EA

---

script/queries/catastrophic_plans_report.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20866](https://devops.dchbx.org/redmine/issues/20866) |
| App-Dev Priority | UP-3 |
| Ticket Author | @karashearer5 |

20866: Pull Data Set from Glue for IVL Notices- Cat Plan Letter IVL_CAP

---

app/models/parsers/edi/incoming_transaction.rb
app/models/parsers/edi/person_loop_validator.rb
spec/models/parsers/edi/etf/person_loop_validator_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21160](https://devops.dchbx.org/redmine/issues/21160) |

21160: Do not propagate post-dated end dates from Carrier terms for IVL enrollments

---

app/models/publishers/trading_partner_edi.rb
spec/models/publishers/trading_partner_edi_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18397](https://devops.dchbx.org/redmine/issues/18397) |

18397: SHOP Carrier swicthes aren't sending a term/cancel to the previous carrier in Production

---

Gemfile.lock

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21235](https://devops.dchbx.org/redmine/issues/21235) |
| Ticket Author | @billy-ran-away |

21235: Update the edi_codec gem in Gluedb

---

app/models/change_sets/identity_change_transmitter.rb
app/models/change_sets/person_dob_change_set.rb
app/models/change_sets/person_gender_change_set.rb
app/models/change_sets/person_name_change_set.rb
app/models/change_sets/person_ssn_change_set.rb
app/models/change_sets/simple_maintenance_transmitter.rb
spec/models/change_sets/identity_change_transmitter_spec.rb
spec/models/change_sets/simple_maintenance_transmitter_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20959](https://devops.dchbx.org/redmine/issues/20959) |

20959: Demographic updates not propagated where we have future terminated and future active policies

---

app/views/enrollment_events/_policy.xml.haml
app/views/layouts/policy_test.xml.haml
spec/support/acapi_vocabulary_spec_helpers.rb
spec/views/enrollment_events/policy.xml.haml_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21435](https://devops.dchbx.org/redmine/issues/21435) |
| Ticket Author | @billy-ran-away |

21435: Bug in relationship_uri generation

---

app/models/parsers/edi/transmission_file.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [17385](https://devops.dchbx.org/redmine/issues/17385) |
| Ticket Author | Cherie Smith |

17385: Relationship Type Correction

---

app/data_migrations/change_enrollee_end_date.rb
lib/tasks/change_enrollee_end_date.rake
spec/data_migrations/change_enrollee_end_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20544](https://devops.dchbx.org/redmine/issues/20544) |

20544: Glue data clean up

---

app/data_migrations/change_enrollee_member_id.rb
app/data_migrations/merge_duplicate_people.rb
lib/tasks/change_enrollee_member_id.rake
spec/data_migrations/change_enrollee_member_id_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21874](https://devops.dchbx.org/redmine/issues/21874) |
| Ticket Author | Camille Gray |

21874: 1095-A look up service not working for multiple Glue accounts

---

app/models/canonical_vocabulary/enrollment_serializer.rb
app/views/policies/_policy_list.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [18141](https://devops.dchbx.org/redmine/issues/18141) |
| Ticket Author | Error Reporting Robot |

18141: gluedb: NoMethodError (undefined method `m_id' for nil: Ni

---

Gemfile.lock

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22932](https://devops.dchbx.org/redmine/issues/22932) |

22932: Bump Glue Gemfile for Changes from 22821

---

app/models/ability.rb
spec/factories/users.rb
spec/models/ability_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [15520](https://devops.dchbx.org/redmine/issues/15520) |
| App-Dev Priority | UP-1 |
| Ticket Author | Alix Pereira |

15520: Grant Kenneth Taylor and Luis Vsquez access to Premium Calculator in Prod and PreProd

---

app/models/enrollment_action/action_publish_helper.rb
app/models/enrollment_action/plan_change.rb
app/models/enrollment_action/plan_change_dependent_add.rb
app/models/enrollment_action/plan_change_dependent_drop.rb
app/models/enrollment_action/termination_date_helper.rb
spec/models/enrollment_action/change_product_member_add_spec.rb
spec/models/enrollment_action/plan_change_dependent_drop_spec.rb
spec/models/enrollment_action/plan_change_spec.rb
spec/models/enrollment_action/termination_date_helper_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20807](https://devops.dchbx.org/redmine/issues/20807) |

20807: Plan change for a COBRA enrollment with Dependent add or drops has Glue incorrectly populating end dates on previous policy

---

script/queries/all_users_by_role.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23049](https://devops.dchbx.org/redmine/issues/23049) |
| App-Dev Priority | n/a |

23049: Update Glue User Audit Query to Include Last Login Time

---

app/data_migrations/generate_audits_via_cv2.rb
spec/data_migrations/generate_audits_via_cv2_spec.rb
spec/factories/enrollees.rb
spec/factories/policies.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [23212](https://devops.dchbx.org/redmine/issues/23212) |

23212: Dependent cancels showing up on audit files

---

script/multiple_aptc_importer.rb
script/queries/current_multi_aptc_values.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [22836](https://devops.dchbx.org/redmine/issues/22836) |

22836: Carefirst SBMI - APTC Credits Table Updates

---

app/data_migrations/remove_enrollee_from_enrollment.rb
lib/tasks/remove_enrollee_from_enrollment.rake
spec/data_migrations/remove_enrollee_from_enrollment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24317](https://devops.dchbx.org/redmine/issues/24317) |
| Ticket Author | Azizza Brown |

24317: Display duplication 

---

app/data_migrations/change_enrollee_end_date.rb
lib/tasks/change_enrollee_end_date.rake
spec/data_migrations/change_enrollee_end_date_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24405](https://devops.dchbx.org/redmine/issues/24405) |

24405: SHOP - Cancel duplicate occurrences of two dependents (HBX ID 19872493)

---

Gemfile
Gemfile.lock
app/data_migrations/update_total_responsible_amount.rb
lib/tasks/update_total_responsible_amount.rake
spec/data_migrations/update_total_responsible_amount_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [26378](https://devops.dchbx.org/redmine/issues/26378) |

26378: KP SBMI prem correction HBX ID # 19912241

---

script/queries/compare_audits.rb
script/queries/compare_non_congress_audits.rb
script/queries/nfp_audit_report.rb
script/queries/nfp_audit_report_non_congress.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [20415](https://devops.dchbx.org/redmine/issues/20415) |
| App-Dev Priority | n/a |

20415: Optimize NFP Audits

---

app/helpers/people_helper.rb
app/models/parsers/edi/incoming_transaction.rb
app/models/policy.rb
app/views/people/_policy_detail.html.erb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24764](https://devops.dchbx.org/redmine/issues/24764) |

24764: Data Synch:  Add Non-Payment Termination Indicator to Glue Policy View UI

---

app/data_migrations/mark_policies_for_non_payment.rb
app/models/policy.rb
lib/tasks/mark_policies_for_non_payment.rake
spec/data_migrations/mark_policies_for_non_payment_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [24765](https://devops.dchbx.org/redmine/issues/24765) |

24765: Data Synch:  Rake Task to set Glue policy non_payment_termination from business validated 2017 and 2018 NPT policy lists

---

app/data_migrations/update_aptc_credits.rb
lib/tasks/update_aptc_credits.rake
spec/data_migrations/update_aptc_credits_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [30131](https://devops.dchbx.org/redmine/issues/30131) |

30131: CMS PBP SBMI Data Errors: APTC Applied and/or Credit Changes - July 2018

---

app/models/external_events/enrollment_event_notification.rb
spec/models/external_events/enrollment_event_notification_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [21822](https://devops.dchbx.org/redmine/issues/21822) |
| Start Date | 02/12/2018 |
| Due Date | 02/26/2018  |
| Development Story Points | 3 |
| Peer Review Story Points | 1 |
| Ticket Author | @davidison |

21822: Initial Enrollment Cancellation 834's

---

app/data_migrations/update_aptc_credits.rb
lib/tasks/update_aptc_credits.rake
spec/data_migrations/update_aptc_credits_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38232](https://devops.dchbx.org/redmine/issues/38232) |

38232: CMS PBP SBMI Data Errors: APTC Applied and/or Credit Changes - Nov 2018

---

app/data_migrations/change_enrollee_premium.rb
lib/tasks/change_enrollee_premium.rake
spec/data_migrations/change_enrollee_premium_spec.rb

|Field|Value|
|-----|-----|
| Redmine Ticket Number | [38275](https://devops.dchbx.org/redmine/issues/38275) |

38275: Duplicate member cleanup in Glue HBX ID # 19901341
